# Generated by Django 2.2.28 on 2023-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Medicine',
        ),
    ]
