# Generated by Django 2.2.28 on 2023-02-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp1', '0002_auto_20230224_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='Brand',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
