# Generated by Django 2.2.28 on 2023-02-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp1', '0003_auto_20230224_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='Price',
        ),
    ]
