# Generated by Django 4.1.7 on 2023-03-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp1', '0004_auto_20230224_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Medicalstore',
        ),
    ]
